#!/bin/sh
#bash <(curl -L https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/license)



else
  echo "add block license server: synosurveillance.synology.com"
  echo "0.0.0.0 synosurveillance.synology.com" | sudo tee -a /etc.defaults/hosts
fi

