#!/bin/sh
#bash <(curl -L https://raw.githubusercontent.com/ZwiReKsyno/Surveillance-Station-2/main/9.2.0_11289/license/remove_license)


# Определите функцию для обработки операций с файлами восстановления.
process_file() {
  local dir="$1"
  local file="$2"
  local backup="$3"
  local mode="$4"

  cd "$dir" || exit

  # Проверьте, существует ли файл резервной копии
  if [ -e "./$backup" ]; then
    rm "./$file"
    mv "./$backup" "./$file"
    chown SurveillanceStation:SurveillanceStation "./$file"
    chmod "$mode" "./$file"
  else
    echo "Error: Backup file $backup does not exist in $dir"
  fi
}


/usr/syno/bin/synopkg stop SurveillanceStation
sleep 5


# Вызов функции для обработки каждого файла
process_file /var/packages/SurveillanceStation/target/lib   libssutils.so     libssutils.so_backup    0644
process_file /var/packages/SurveillanceStation/target/sbin  sscmshostd        sscmshostd_backup       0755
process_file /var/packages/SurveillanceStation/target/sbin  sscored           sscored_backup          0755
process_file /var/packages/SurveillanceStation/target/sbin  ssdaemonmonitord  ssdaemonmonitord_backup 0755
process_file /var/packages/SurveillanceStation/target/sbin  ssexechelperd     ssexechelperd_backup    0755
process_file /var/packages/SurveillanceStation/target/sbin  ssroutined        ssroutined_backup       0755
process_file /var/packages/SurveillanceStation/target/sbin  ssmessaged        ssmessaged_backup       0755

 

sleep 5
/usr/syno/bin/synopkg start SurveillanceStation
