#!/bin/sh
#bash <(curl -L https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/9.2.0_11289/SurveillanceStation-armada375/install_license)


# Блокировать сервер аутентификаци
if grep -q "synosurveillance.synology.com" /etc/hosts; then
  echo "already blocked license server: synosurveillance.synology.com."
else
  echo "add block license server: synosurveillance.synology.com"
  echo "0.0.0.0 synosurveillance.synology.com" | sudo tee -a /etc/hosts
fi


# Определить функции для обработки файлов
process_file() {
  local dir="$1"
  local file="$2"
  local url="$3"
  local mode="$4"

  cd "$dir" || exit
  cp ./"$file" ./"$file"_backup
  rm ./"$file"
  wget "$url" -O ./"$file"
  chown SurveillanceStation:SurveillanceStation ./"$file"
  chmod "$mode" ./"$file"
}


/usr/syno/bin/synopkg stop SurveillanceStation
sleep 5


# Обработка каждого файла
process_file /var/packages/SurveillanceStation/target/lib  libssutils.so    https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/9.2.0_11289/SurveillanceStation-armada375/libssutils.so     0644
process_file /var/packages/SurveillanceStation/target/sbin sscmshostd       https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/9.2.0_11289/SurveillanceStation-armada375/sscmshostd        0755
process_file /var/packages/SurveillanceStation/target/sbin sscored          https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/9.2.0_11289/SurveillanceStation-armada375/sscored           0755
process_file /var/packages/SurveillanceStation/target/sbin ssdaemonmonitord https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/9.2.0_11289/SurveillanceStation-armada375/ssdaemonmonitord  0755
process_file /var/packages/SurveillanceStation/target/sbin ssexechelperd    https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/9.2.0_11289/SurveillanceStation-armada375/ssexechelperd     0755
process_file /var/packages/SurveillanceStation/target/sbin ssroutined       https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/9.2.0_11289/SurveillanceStation-armada375/ssroutined        0755
process_file /var/packages/SurveillanceStation/target/sbin ssmessaged       https://github.com/ZwiReKsyno/Surveillance-Station-2/raw/main/9.2.0_11289/SurveillanceStation-armada375/ssmessaged        0755


sleep 5
/usr/syno/bin/synopkg start SurveillanceStation
